apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit
spec:
  replicas: 1 # 1 pod  but i can increase multiple pods that the main purpose of using kubernetes for scaling and load balancing so based on user traffic i can increase the number of pods and kubernetes will automatically load balance the traffic between the pods
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit-container
          image: streamlit-app:latest # this should match the image name you used in docker build
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: llmops-secrets # this for the secret we created with kubectl create secret generic
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service # this is the name of the service, you can choose any name you like
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80 # this is the port that will be exposed outside the cluster
      targetPort: 8501 # this streamlit's default port, it should match the containerPort in the deployment